# Generated by Django 3.2.6 on 2021-10-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_line', models.TextField(default='', max_length=50)),
                ('default_language', models.IntegerField(choices=[(0, 'C++11'), (1, 'C++14'), (2, 'C++17'), (3, 'C++20'), (4, 'C11'), (5, 'C90'), (6, 'C99'), (7, 'Python2'), (8, 'Python3'), (9, 'Java 8'), (10, 'Java 11')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
