# Generated by Django 3.2.6 on 2021-10-24 09:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('example_input', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('example_output', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('limit_description', models.TextField(blank=True, null=True)),
                ('accepted', models.IntegerField(default=0)),
                ('wrong_answer', models.IntegerField(default=0)),
                ('compilation_error', models.IntegerField(default=0)),
                ('runtime_error', models.IntegerField(default=0)),
                ('time_limit_exceeded', models.IntegerField(default=0)),
                ('memory_limit_exceeded', models.IntegerField(default=0)),
                ('unknown_error', models.IntegerField(default=0)),
                ('is_public', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=65535)),
                ('language', models.IntegerField(choices=[(0, 'C++11'), (1, 'C++14'), (2, 'C++17'), (3, 'C++20'), (4, 'C11'), (5, 'C90'), (6, 'C99'), (7, 'Python2'), (8, 'Python3'), (9, 'Java 8'), (10, 'Java 11')], default=1)),
                ('memory', models.IntegerField(blank=True, default=None, null=True)),
                ('time', models.IntegerField(blank=True, default=None, null=True)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(choices=[(0, '채점 준비 중'), (1, '채점 중'), (2, '맞았습니다'), (3, '틀렸습니다'), (4, '컴파일 에러'), (5, '런타임 에러'), (6, '시간 초과'), (7, '메모리 초과'), (8, '알 수 없는 오류')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
    ]
